/*
 * Copyright 2025 ThatScalaGuy
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package fs2.nats.client

import cats.effect.IO
import com.comcast.ip4s.{Host, Port}
import fs2.Chunk
import fs2.io.net.Network
import fs2.io.net.tls.TLSContext
import munit.CatsEffectSuite

import java.security.KeyStore
import javax.net.ssl.{KeyManagerFactory, SSLContext, TrustManagerFactory}
import scala.concurrent.duration.*

/** Integration tests for TLS and mutual-TLS connections.
  *
  * Requires the TLS brokers, which use certs generated by
  * integration/src/test/resources/tls/gen-certs.sh:
  *
  *   - nats-tls (port 4227): one-way TLS, no client cert required
  *   - nats-mtls (port 4228): mutual TLS, verify:true
  *
  * Start them with: docker compose up -d nats-tls nats-mtls
  */
class TlsIntegrationSpec extends CatsEffectSuite:

  override def munitTimeout: Duration = 60.seconds

  private val natsHost = Host.fromString("localhost").get
  private val tlsPort = Port.fromInt(4227).get
  private val mtlsPort = Port.fromInt(4228).get

  private val KeystorePass = "password".toCharArray

  private def loadKeyStore(resource: String): KeyStore =
    val ks = KeyStore.getInstance("PKCS12")
    val is = getClass.getResourceAsStream(resource)
    assert(is != null, s"missing test resource $resource")
    try ks.load(is, KeystorePass)
    finally is.close()
    ks

  /** Build a JVM SSLContext trusting the test CA, optionally presenting the
    * client certificate for mutual TLS.
    */
  private def sslContext(withClientCert: Boolean): SSLContext =
    val tmf =
      TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm)
    tmf.init(loadKeyStore("/tls/truststore.p12"))

    val keyManagers =
      if withClientCert then
        val kmf =
          KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm)
        kmf.init(loadKeyStore("/tls/client.p12"), KeystorePass)
        kmf.getKeyManagers
      else null

    val ctx = SSLContext.getInstance("TLS")
    ctx.init(keyManagers, tmf.getTrustManagers, null)
    ctx

  private def tlsContext(withClientCert: Boolean): TLSContext[IO] =
    Network[IO].tlsContext.fromSSLContext(sslContext(withClientCert))

  private def configFor(port: Port) = ClientConfig(
    host = natsHost,
    port = port,
    useTls = true,
    backoff = BackoffConfig.fast.copy(maxRetries = Some(2))
  )

  private def roundTrip(client: NatsClient[IO]): IO[String] =
    val subject = s"tls.test.${System.currentTimeMillis()}"
    client.subscribe(subject).use { msgStream =>
      for
        _ <- IO.sleep(100.millis)
        _ <- client.publish(subject, Chunk.array("encrypted".getBytes))
        msg <- msgStream.take(1).timeout(5.seconds).compile.lastOrError
      yield msg.payloadAsString
    }

  test("one-way TLS: trusting the CA connects and round-trips") {
    NatsClient
      .connect[IO](configFor(tlsPort), tlsContext = Some(tlsContext(false)))
      .use(roundTrip)
      .map(assertEquals(_, "encrypted"))
      .timeout(15.seconds)
  }

  test("mutual TLS: presenting the client cert connects and round-trips") {
    NatsClient
      .connect[IO](configFor(mtlsPort), tlsContext = Some(tlsContext(true)))
      .use(roundTrip)
      .map(assertEquals(_, "encrypted"))
      .timeout(15.seconds)
  }

  test("mutual TLS: connecting without a client cert is rejected") {
    NatsClient
      .connect[IO](configFor(mtlsPort), tlsContext = Some(tlsContext(false)))
      .use(roundTrip)
      .timeout(10.seconds)
      .attempt
      .map(result =>
        assert(
          result.isLeft,
          "mTLS broker accepted a connection without a client certificate"
        )
      )
  }
